### ISSUE TITLE
LSTM Dropout

### ISSUE THREAD

**Issue by JackKelly** [craffel/nntools#10]
I just wanted to ask if there are any plans to implement the dropout ideas from [Zaremba _et al._ 2014](arxiv.org/pdf/1409.2329.pdf) in Lasagne?

From reading the ["Recurrence" issue](https://github.com/benanne/Lasagne/issues/17#issuecomment-69194705) on benanne/Lasagne, I understood that @skaae has implemented Zaremba _et al._'s ideas in his fork but there was some question about the most consistent / natural way to implement these ideas in Lasagne.  Is that correct?

(If I can get my network to overfit; and if I get some time then I could possibly do some work on this if needed ;)

**Comment by craffel** [comment]
We'll need to implement a `CustomLSTMLayer` a la the `CustomRecurrentLayer` that already exists.  It's something we need to do at some point, but I'm uncertain we'll be able to have a `CustomLSTMLayer` which has all of the optimizations which makes the `LSTMLayer` worth using at all.  If you're not getting overfitting yet, I wouldn't sweat it; I think needing dropout in recurrent nets is still very uncommon right now.

**Comment by skaae** [comment]
I have it implemented in my fork: https://github.com/skaae/nntools

best regards Søren

**Comment by skaae** [comment]
Sorry didn't read the rest of your post :)

**Comment by JackKelly** [comment]
> If you're not getting overfitting yet, I wouldn't sweat it;
> I think needing dropout in recurrent nets is still very uncommon right now.

OK, that sounds like good advice!

> I'm uncertain we'll be able to have a CustomLSTMLayer which has
> all of the optimizations which makes the LSTMLayer worth using at all.

Sure.  Is that an argument for baking the dropout code into the LSTM class (like in @skaae's fork)?  The thinking being that you can still have all the lovely optimizations but you can also have precisely-targeted dropout.  Although I do appreciate that it would be nice to have a consistent way to implement dropout across Lasagne.  And I also appreciate that I'm super-new to Lasagne so I'm really in no position to dive into design discussions!

**Comment by craffel** [comment]
> Although I do appreciate that it would be nice to have a consistent way to implement dropout across Lasagne.

Yeah, this is exactly the issue.  As a rough guide, we are only including things in classes that are so fundamentally useful to that they need to baked in to the class, e.g. peephole connections or learning the initial state for LSTM layers.  I don't believe dropout in LSTM layers is there yet.

**Comment by JackKelly** [comment]
Sure, I understand.  Thanks for the very quick & informative replies.

**Comment by craffel** [comment]
I was talking to Wojciech today and had another look at his paper and I think that applying his style of dropout is actually currently possible using this repo's `LSTMLayer` and the `DropoutLayer`.  As I understand Wojciech's paper, he is only applying dropout on the connections between layers, but not on the recurrent connections within layers.  As currently implemented, you can't apply dropout to the recurrent connections because they are defined and fixed within the layer.  But, that's OK, because we aren't supposed to drop out those connections.  Applying dropout between layers should then be as simple as adding a dropout layer between stacked LSTM layers.  

However, the way @skaae has implemented it, dropout is applied after the input mix is computed, i.e. `input_dot_W = D(T.dot(input, self.W_in_to_gates))` here:
https://github.com/skaae/nntools/blob/master/lasagne/layers/recurrent.py#L402
which we couldn't do with the current implementation.  However, based on the equation and image on page 3 of the paper, it looks like dropout needs to be applied to the input. i.e. `input_dot_W = T.dot(D(input), self.W_in_to_gates)`, which we can do. So, unless I'm mistaken, we can already implement dropout of this particular type.  Any objections?

**Comment by skaae** [comment]
I think you are correct. 
If T is the linear transform then dropout is applied before the the input mix according to the equations on page 2. 

Don't know if it matters though?

**Comment by JackKelly** [comment]
This all sounds very positive, thank you ;)  I'll probably test putting dropout in between LSTM layers quite soon.

**Comment by craffel** [comment]
> I think you are correct.  ... Don't know if it matters though?

Yes, I'm not sure if it will matter in practice, but the reason it matters to us is that we can implement it without adding any functionality to `LSTMLayer` or creating a `CustomLSTMLayer`.  So I'm going to close this issue for now, @JackKelly if you encounter any issues feel free to report them here.

**Comment by hbyido** [comment]
hi，@jackkelly， i am interesting your work about lstm in anomaly detection，do you have the paper and the code about it ？

 https://www-304.ibm.com/connections/blogs/et/entry/automatic_detection_of_anomalies_in_sensor_data_from_buildings?lang=zh_cn，

**Comment by JackKelly** [comment]
@hbyido no, I'm afraid that was an internal project at IBM, so there is no paper or code, I'm sorry (I didn't do anything very clever though!)
