### ISSUE TITLE
recurrent example

### ISSUE THREAD

**Issue by skaae** [craffel/nntools#59]
In the recurrent example there is a single target for each seqeuence. 

In https://github.com/craffel/nntools/blob/recurrent/examples/recurrent.py#L140 you take the 
last output from the recurrent network and use that to compute the error. 

For the forward RNN it makes sense to take the last output, but for the backwards RNN im not sure? 

For the backwards RNN we parse backwards and then reverse the sequence, that means that we should probably make the prediction from position 0 in the backwards RNN? 

I guess the correct thing would be to use a slice layer before the sum layer?

**Comment by craffel** [comment]
> For the backwards RNN we parse backwards and then reverse the sequence, that means that we should probably make the prediction from position 0 in the backwards RNN?

Yes, I think you're right.

> I guess the correct thing would be to use a slice layer before the sum layer?

This actually seems better either way as it will save a lot of computation - otherwise the dense layer will be computing the output for every time step, but we only need it to do so for the last one. If we use a slice layer, we can omit the `ReshapeLayer`s.  This makes the example less illustrative, but we already have an example of how to use `ReshapeLayer`s within the `recurrent.py` docstring, so I don't think that's so bad.

**Comment by skaae** [comment]
I used  SliceLayer when i had a similar problem. I thinks its a good example and it's not that easy to figure out.

**Comment by craffel** [comment]
Implemented in 3df009b, what do you think?

**Comment by skaae** [comment]
Looks good to me
