### ISSUE TITLE
Simple LSTM failing due undefined input dimension

### ISSUE THREAD

**Issue by lucas0** [craffel/nntools#65]
I'm trying to build an LSTM model for classifying the ATIS dataset. 

From a sentence of undefined size N, I generate a _context window word embedding matrix_. That's what I need to feed on my model, but I can't figure out how to make it so.

When I define my input layer as:

```
def build_lstm(input_var=None):
    l_in = lasagne.layers.InputLayer(shape=(None, 1, None, None), input_var=input_var)
    l_hid = l_lstm = lasagne.layers.LSTMLayer(l_in, num_units=300)
    l_out = lasagne.layers.DenseLayer(l_hid, num_units=127, nonlinearity=lasagne.nonlinearities.softmax)

return l_out
```

I get:

```
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
```

While if I define the input shape in the l_in declaration it works, for example:

```
l_in = lasagne.layers.InputLayer(shape=(None, 1, 30, 30), input_var=input_var)
```

The point is that each sentence has a different size, thus resulting in a _context window word embedding matrix_ of different shape. What can I do?

**Comment by craffel** [comment]
You'll need to use different shape conventions.  You can't have a final dimension which will change.  Please note that the recurrent layers from this repository have been merged upstream, so that's the correct place to report issues.  This isn't an issue though, it's a usage question, for this stuff you should post to the lasagne-users google group.
